name: release

permissions:
    contents: write

on:
    push:
        tags:
            - "*"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Node.js and Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Authentication
              run: |
                  echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Install dependencies
              run: bun install

            - name: Publish packages
              run: bun run version:publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create GitHub Release
              run: bun run version:release
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
